### PR TITLE
Add 19123 to base

### PR DESCRIPTION
**Pull request by ejbleys**
XSDs from OGC

### CODE REVIEW

**Comment by ronaldtse** [comment]
@ejbleys looks like we should merge this?

**Comment by ejbleys** [comment]
I’ll get back to you on this
Evert Bleys
4 Tudor Place HUGHES ACT 2605
Australia
+61 (0)2 62811773
+61 (0)411 483 876
ejbleys@gmail.com
Skype ejbleijs@gmail.com

**Comment by ejbleys** [comment]
Reject the original (#18) pull request
The directory name is wrong (cit: where did that come from?)
	(once again - I can’t work out how to dump a file/directory from my fork)
I have copied the content into new directory is …/19123/-2/gmlcov/1.0/ 
[Query: Can you do a pull directly from the OGC repo or do I have to copy into my fork {,as I have done}?]

I have sent a query to Knut re: namespace URLs; gml version
	suspect the new location is good-to-go but I’ll create a pull request once sure
Once I have checked that, I’ll put in a new pull request.

Cheers
e
Evert Bleys
4 Tudor Place HUGHES ACT 2605
Australia
+61 (0)2 62811773
+61 (0)411 483 876
ejbleys@gmail.com
Skype ejbleijs@gmail.com

**Comment by ronaldtse** [comment]
> Reject the original (#18) pull request
>The directory name is wrong (cit: where did that come from?)
>	(once again - I can’t work out how to dump a file/directory from my fork)

@ejbleys you can actually modify your own fork, and there's no need for a new Pull Request (PR).

If you change your local fork, the PR here will get updated.

**Comment by ejbleys** [comment]
My skills in GitHub management are quite obviously limiting - How?
Evert Bleys
4 Tudor Place HUGHES ACT 2605
Australia
+61 (0)2 62811773
+61 (0)411 483 876
ejbleys@gmail.com
Skype ejbleijs@gmail.com

**Comment by ejbleys** [comment]
Got it, sorry
Evert Bleys
4 Tudor Place HUGHES ACT 2605
Australia
+61 (0)2 62811773
+61 (0)411 483 876
ejbleys@gmail.com
Skype ejbleijs@gmail.com

**Comment by ronaldtse** [comment]
@ejbleys you got it! Sorry didn't see the message in time. Regarding resolving the conflicts, you can do the following:

```
git remote add tc211 https://github.com/ISO-TC211/schemas
git fetch tc211
git merge tc211/master
```

This will allow you to merge the current changes in your fork with the content in the main repository (the non-forked repo). During the merge operation, you may need to manually edit some files to resolve the changes made in both branches (that's why they conflict each other).

**Comment by ejbleys** [comment]
Hi Ronald

ISO 19123-2 is now good to go 
We will work out where the ISO authoritative master lives later
Either way a copy should exist in ISO repository
    with a read-me on where the authoritative copy lies (OGC or ISO)
     - discussion for XMG in Omiya

Cheers
e
Evert Bleys
4 Tudor Place HUGHES ACT 2605
Australia
+61 (0)2 62811773
+61 (0)411 483 876
ejbleys@gmail.com
Skype ejbleijs@gmail.com

**Pull request closed without merging**
