### PR TITLE
extended.xsd

### PR DESCRIPTION
**Pull request by ejbleys**
Proposal: - initiate ISO 19135-1 XSDs

pir.xsd - base for ISO 19135-1 
hierarchy.xsd
extended.xsd (this request)

### CODE REVIEW

**Comment by PeterParslow** [comment]
This great work by Evert is with the 19135-1 Amendment team for testing/evaluation.

**Comment by PeterParslow** [comment]
This great work by Evert is with the 19135-1 Amendment team for testing/evaluation.

**Comment by ronaldtse** [comment]
@ejbleys @PeterParslow do we need extra input or can we merge this? Thanks!

**Comment by ejbleys** [comment]
Please merge
Evert Bleys
4 Tudor Place HUGHES ACT 2605
Australia
+61 (0)2 62811773
+61 (0)411 483 876
ejbleys@gmail.com
Skype ejbleijs@gmail.com

**Comment by PeterParslow** [comment]
Status is a 'working draft'; it is with the project team, who will discuss it on 25th November (hopefully more of them having tested it!), and then at WG9 in Omiya.

**Pull request merged**
