### PR TITLE
Add ISO 19139 schemas from standards.iso.org

### LINKED ISSUE #24: Removal of ISO resources under https://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas
Dear all,
on behalf of the INSPIRE team, I am writing to ask for some explanation of the recent removal of all the resources under https://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas. These include the schema http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gmd/gmd.xsd, which is referenced in other widely-used schemas.

This breaking change is already causing issues in the INSPIRE validation community - see for example [[1](https://github.com/inspire-eu-validation/community/issues/245)], [[2](https://github.com/inspire-eu-validation/community/issues/246)], [[3](https://github.com/inspire-eu-validation/community/issues/247)], [[4](https://inspire.ec.europa.eu/forum/discussion/view/264812/iso-ap-100-schemalocation-to-iso-website-not-available)].

Can you please inform us whether this is just a temporary or a permanent change?
Thank you.

### PR DESCRIPTION
**Pull request by ronaldtse**
Return of `https://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas` under `https://schemas.isotc211.org/19139/-/`.

This hopefully resolves #24 .

### CODE REVIEW

**Comment by PeterParslow** [comment]
Is this to be part of a long term managed transition away from the ISO website? If so, how is that to be communicated to the many implementations that use these resources - not just the schemas, but (perhaps even more!) the code lists.

**Comment by ronaldtse** [comment]
@PeterParslow It was previously resolved that new schemas are to be distributed via schemas.isotc211.org instead of standards.iso.org as electronic inserts.

The relevant resolution is Resolution 857: "Official web access for ISO/TC 211 resources to support implementation of standards".

> ISO/TC 211 resolves to use isotc211.org for web access to its official resources that support implementation, including but not limited to, XML Implementation Schemas, XML Codelists, XML Example files, Ontologies, UML XMI files, Terminologies and Profiles of standards.

I don't think there was a particular resolution about "migrating old files" from standards.iso.org, but given that the `www.isotc211.org/2005` namespace falls under a similar category (schemas from withdrawn standards but still used), it makes sense in keeping a copy in schemas.isotc211.org.

Would you suggest otherwise?

**Comment by PeterParslow** [comment]
"Would you suggest otherwise?" - not at all - I strongly prefer old things to stay where they are. 
The December 2019 TC debated a resolution to state that our resources should remain in place; it arose from a long discussion on persistence & backward compatibility. We didn't pass a resolution because the various maintenance group convenors said that that's what they did anyway!

Hence my desire that we (TC211) raise it with ISO. Actually, perhaps I'll just email Mats myself.

**Comment by ronaldtse** [comment]
@PeterParslow it's fine either way. Personally I find it easier to answer the requests we have been receiving, if we have confidence that we have everything in one consistent and well-maintained place (even if the old place still exists).

**Comment by PeterParslow** [comment]
@ronaldtse "answer requests" is a valid but distinct use cases from public direct use of the schema files.

In a similar way, many validators can be set to deliberately cache a copy locally - that's why it's the namespace identifier that formally identifies the schema, with the instance schemaLocation just being a hint (albeit, a hint that many take very seriously!). Problems arise when standards bodies change things in the XSDs without changing the namespace identifier. And during the life of 19139, both W3C and OGC have done that!

INSPIRE are looking at changing their import schemaLocations to the OGC addresses, which will work. But is a sign that they now consider them more reliable schema hosts than ISO (not, strictly, 'than TC211').

**Comment by ejbleys** [comment]
Thanks Peter, that answers a question I had on a completely different issue
Cheers
Evert
Evert Bleys
4 Tudor Place HUGHES ACT 2605
Australia
+61 (0)2 62811773
+61 (0)411 483 876
ejbleys@gmail.com
Skype ejbleijs@gmail.com

**Comment by ronaldtse** [comment]
Thanks @PeterParslow : a shame for ISO schema locations to be less reliable than OGC (a fact), but perhaps we are obliged to try fixing this, before throwing in the towel... 😉

**Comment by ejbleys** [comment]
Hi Peter
That is exactly what tc 211are trying to do.
It will cause some issues in the short term but increase stability in the long term
Cheers
e 
Evert Bleys
4 Tudor Place HUGHES ACT 2605
Australia
+61 (0)2 62811773
+61 (0)411 483 876
ejbleys@gmail.com
Skype ejbleijs@gmail.com

**Comment by ronaldtse** [comment]
This is superseded by 842920a533e7b8ddd8a95c95a6a3bb6f373f6ace . Closing.

**Pull request closed without merging**
