### PR TITLE
ISO-TC211/schemas.isotc211.org#10 trigger schemas.isotc211.org deployment on push

### PR DESCRIPTION
**Pull request by CAMOBAP**
- ISO-TC211/schemas.isotc211.org#10

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP795 can we use an existing marketplace action like this: https://github.com/marketplace/actions/webhook-trigger ?

**Comment by CAMOBAP** [comment]
Yep, this is how it will look like:

```
...
- name: Trigger another repo build
  uses: zzzze/webhook-trigger@master
  with:
    data: "{\"event_type\":\"deploy_staging\"}"
    webhook_url: https://api.github.com/repos/ISO-TC211/schemas.isotc211.org/dispatches
    options: "-H \"Accept: application/vnd.github.everest-preview+json\" -H \"Content-Type: application/json\""
   user: "${{ secrets.PAT_USERNAME }}:${{ secrets.PAT_TOKEN }}"
```

To be honest it doesn't look like a simpler solution, because this action was developed for general WebHook

I think we can make better action if we decided to make action specially for triggering other workflows, this is how it may look like:

```
...
- name: Trigger another repo build
  uses: metanorma/repository-dispatch@master
  with:
    event_type: "{\"event_type\":\"deploy_staging\"}"
    repository: ISO-TC211/schemas
    payload: {...} 
    token: "${{ secret.PAT_TOKEN}}"
```

**Comment by CAMOBAP** [comment]
**Update!!!**

@ronaldtse 

https://github.com/marketplace/actions/repository-dispatch - this is exactly what we are looking

Should I move to it?

**Comment by ronaldtse** [comment]
Excellent!

**Comment by CAMOBAP** [comment]
@ronaldtse done

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP795 !

**Comment by ronaldtse** [comment]
@CAMOBAP795 issue found:

- Your workflow file was invalid: The pipeline is not valid. .github/workflows/deploy.yml (Line: 13, Col: 13): Unrecognized named-value: 'event_type'. Located at position 1 within expression: event_type

Can you please help?

**Comment by ejbleys** [comment]
Can anyone tell me how/where the HTML code for https://schemas.isotc211.org/schemas <https://schemas.isotc211.org/schemas> is managed?
Or does it happen auto-magically? (I doubt it somehow!)
EG are the links on that page just added to the end of the list, or is the page curated?

Cheers
E
Evert Bleys
4 Tudor Place HUGHES ACT 2605
Australia
+61 (0)2 62811773
+61 (0)411 483 876
ejbleys@gmail.com
Skype ejbleijs@gmail.com

**Comment by ronaldtse** [comment]
@ejbleys The HTML code is managed here: https://github.com/ISO-TC211/schemas.isotc211.org

The page is curated manually but submodules this current repo for data. We're still fixing the trigger.

**Comment by ejbleys** [comment]
I was just looking at the order of standards in the HTML and wondering ...
Evert Bleys
4 Tudor Place HUGHES ACT 2605
Australia
+61 (0)2 62811773
+61 (0)411 483 876
ejbleys@gmail.com
Skype ejbleijs@gmail.com

**Comment by ronaldtse** [comment]
@ejbleys the schema HTMLs are auto-generated -- I see what you mean -- we can order them.

**Comment by ejbleys** [comment]
Hi Guys
Has the source for https://schemas.isotc211.org/ <https://schemas.isotc211.org/> changed?
I was convinced it had been https://github.com/ISO-TC211/schemas <https://github.com/ISO-TC211/schemas>
The link on the TC211 page now takes users to https://github.com/ISO-TC211/XML <https://github.com/ISO-TC211/XML> which, as far as I know, is not correct.
	that page is for XLM maintenance, not publication.
Cheers
E
Evert Bleys
Convenor ISO TC 211 XML Maintenance Group
4 Tudor Place
HUGHES ACT 2605
Australia
email:  ejbleys@gmail.com
Mob:   +61 (0)411 483 876
Land:  +61 (0)2 6281 1773
Skype: ejbleijs@gmail.com

**Pull request merged**
